alias jupy='(cd ~/Code/MyCodes/Jupyter && conda activate && jupyter notebook && conda deactivate)'
alias git-update='git add --all && git commit -m "Subhrajyoti: $(date "+%Y-%m-%d %H:%M:%S")" && git push'
alias bash='bash -x'
alias install='sudo bash ~/.system/install-fedora.sh'
alias update='sudo bash ~/.system/update-fedora.sh'
